package Exceptions;
import java.util.Scanner;

@SuppressWarnings("unused")
// class Test{
//   static int divideByZero(int a , int b){
//     int i = a/b;
//     return i;
//     }
//
//     static int computeDivision(int a, int b){
//       int res = 0;
//       try{
//         res = divideByZero(a,b);
//       } catch (NumberFormatException NFE){
//         System.out.println("NumberFormatException occured.");
//       }
//       return res;
//     }
//
//     public static void main(String[] args) {
//       Scanner scan = new Scanner(System.in);
//       int a = scan.nextInt();
//       int b = scan.nextInt();
//
//       try{
//         int i = computeDivision(a,b);
//       } catch(ArithmeticException ae){
//         System.out.println(ae.getMessage());
//       }
//     }
// }


class Test{
  public static void main(String[] args) {
    int [] arr = new int[4];
    int i = arr[4];
    System.out.println("Hi, lets execute.\n");
  }
}
